### ISSUE TITLE
Export Trello JSON

### ISSUE THREAD

**Issue by Lewiscowles1986** [HelloKitty/Atvaarks.Old.HO.Server.Emulator#1]
any way to export trello JSON so I can put it in a WeKan? I like to archive software, so it's amazing to be able to have notes as well

**Comment by HelloKitty** [comment]
@Lewiscowles1986 I may still have the Trello board.

**Comment by HelloKitty** [comment]
@Lewiscowles1986 Here is the exported board https://pastebin.com/paKL5NNv
